---
driver:
  name: docker
  privileged: true

provisioner:
  name: chef_zero
  attributes:
    test-kitchen: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: recipe[install-apache]