---
driver:
  name: docker
  use_sudo: false

# If you add new platforms below, include them in the .travis.yml file matrix
platforms:
- name: centos-7
# W: Failed to fetch http://httpredir.debian.org/debian/dists/squeeze/main/binary-amd64/Packages.gz  404  Not Found [IP: 5.153.231.35 80]
# - name: debian-6
#   run_list: recipe[apt]
- name: ubuntu-16.04
  run_list: recipe[apt]
