---
driver:
  name: docker

platforms:
- name: ubuntu-16.04
  run_list: recipe[install-apache]
- name: centos-7
driver_config:
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - systemctl enable sshd.service