---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_license: accept

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04


verifier:
  name: inspec
  
suites:
  - name: default
    run_list:
      - recipe[install-apache::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
