sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - curl

before_install:
- curl -s https://packages.chef.io/files/stable/chefdk/4.7.73/ubuntu/16.04/chefdk_4.7.73-1_amd64.deb | bash


# Don't `bundle install` which takes about 1.5 mins
install: 
- apt-get install chefdk
- echo "skip bundle install"
gemfile: gemfiles/Gemfile.ci

branches:
  only:
    - master

services: docker

env:
  global:
  - KITCHEN_YAML=.kitchen.yml
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
  matrix:
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: kitchen test ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1