sudo: required
dist: trusty

before_install:
- curl -s https://packagecloud.io/install/repositories/chef/stable/script.deb.sh | sudo bash

# Don't `bundle install` which takes about 1.5 mins
install: 
- sudo apt-get install chefdk
- echo "skip bundle install"
gemfile: gemfiles/Gemfile.ci

branches:
  only:
    - master

services: docker

env:
  global:
  - KITCHEN_YAML=.kitchen.yml
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
  matrix:
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: kitchen test ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1