[local_phases]
unit = "rspec spec/"
lint = 'cookstyle --display-cop-names --extra-details'
syntax = "foodcritic ."
smoke = "chef exec kitchen test"
provision = "echo skipping"
deploy = "echo skipping"
functional = "echo skipping"
cleanup = "echo skipping"